name: statcull
channels:
  - pytorch 
  - conda-forge
dependencies:
  - python>=3.11
  - numpy>=1.24
  - pytorch>=2.6.*
  - pip
  - pip:
      - -e .                # install your package in editable mode (assumes pyproject.toml/setup.cfg present)
